numeric: numeric.cpp parsing.h parsing.cpp parsing_define.h parsing_define.cpp parsing_eval.h helpers.h helpers.cpp parsing_gradient.h parsing_mcint.h parsing_numint.h parsing_eval.cpp parsing_gradient.cpp parsing_mcint.cpp parsing_numint.cpp 
	g++ -o numeric -ggdb3 -Wall -Werror -pedantic -std=gnu++11 numeric.cpp parsing.h parsing.cpp parsing_define.h parsing_define.cpp parsing_eval.h helpers.h helpers.cpp parsing_gradient.h parsing_mcint.h parsing_numint.h parsing_eval.cpp parsing_gradient.cpp parsing_mcint.cpp parsing_numint.cpp

clean:
	rm -f *~ *.o numeric
